<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Async & Await</title>
	</head>
	<body>
		<script>
			// const getIDs = () =>
			// 	new Promise((resolve, reject) => {
			// 		setTimeout(() => {
			// 			resolve([532, 543, 753, 1, 5]);
			// 		}, 1500);
			// 	});
			// const getRecipe = (recipeID) => {
			// 	return new Promise((resolve, reject) => {
			// 		setTimeout(
			// 			(ID) => {
			// 				const recipe = {
			// 					title: "Fresh tomato pasta",
			// 					publisher: "Pinchas Hodadad",
			// 				};
			// 				resolve(`${ID}: ${recipe.title}`);
			// 			},
			// 			1500,
			// 			recipeID
			// 		);
			// 	});
			// };
			// getIDs()
			// 	.then((IDs) => {
			// 		console.log(IDs);
			// 		return getRecipe(IDs[2]);
			// 	})
			// 	.then((recipe) => {
			// 		console.log(recipe);
			// 	})
			// 	.catch((error) => {
			// 		console.log("It is an error!");
			// 	});
			const getIDsModern = async () => {
				return [532, 543, 753, 1, 5];
			};
			const getRecipeModern = async (recipeID) => {
				const recipe = {
					title: "Fresh tomato pasta",
					publisher: "Pinchas Hodadad",
				};
				return `${recipeID[2]}: ${recipe.title}`;
			};
			const getRecipeById = async () => {
				const id = await getIDsModern();
				const recipe = await getRecipeModern(id);
				console.log(recipe);
			};
			getRecipeById().catch((e) => {
				console.error(e);
			});
		</script>
	</body>
</html>
